### ISSUE TITLE
Roadmap and contributing guidelines

### ISSUE THREAD

**Issue by nunosilva800** [CityOfZion/neo-ruby#2]
Heyo!

I noticed there's a [TODOs.md](https://github.com/CityOfZion/neo-ruby/blob/master/TODOs.md) file which is very consise and mostly done with.

I was wondering if we should start a proper roadmap as well as contributing guidelines.
The roadmap can either be a file, an entry on the wiki, or just plain old GH issues.

Some of the things I think are actionable as of right now:

- [x] write the contributing.md file
- [ ] Fix rubocop offenses
- [ ] Add rubocop to the CI
- [ ] Write usage examples / code examples

WDYT?

**Comment by nunosilva800** [comment]
@ambethia bump

**Comment by ambethia** [comment]
Yes absolutely. I'm still in the position where I'm going to be doing a lot of refactoring and moving pieces around, but as soon as the dust settles this will be a priority.

For example, I think I might be merging this and the `neo-ruby-sdk` repo to work towards creating a full node in ruby, not just a light client.

**Comment by ambethia** [comment]
This is definitely something I could use some help on.

**Comment by nunosilva800** [comment]
Yes! During next week, I can keep on cleaning the code and fixing rubocop warnings (what remains here requires some big refactors, most of them are already annotated with a TODO).

Regarding the exact roadmap, I'm thinking we should look at the reference implementation and define which missing parts are more important to tacke. 

We should have a channel over on discord, specific to ruby, so that it's easier to communicate.
